### ISSUE TITLE
Mozilla's Global Sprint (June 1st and 2nd 2017)

### ISSUE THREAD

**Issue by bmpvieira** [bionode/bionode#44]
## About
"[Mozilla’s Global Sprint is a fun](https://mozilla.github.io/global-sprint/), fast-paced and two-day collaborative event to hack and build projects for a healthy Internet. A diverse network of scientists, educators, artists, engineers and others come together in person and online to innovate in the open. [Get your tickets now!](https://mozilla.github.io/global-sprint/register)"

## Communication channels
Come chat with us at [http://gitter.im/bionode/bionode](http://gitter.im/bionode/bionode) or IRC (freenode) #bionode!

### Very little or no programming knowledge required:
- [x] Make sure all repos have the up to date special files (README, LICENSE, etc) such as [bionode/bionode](https://github.com/bionode/bionode): [bionode #38](https://github.com/bionode/bionode/issues/38)
- [x] Make sure all repos follow the JavaScript Standard style guide: [bionode #26](https://github.com/bionode/bionode/issues/26)
- [x] Add missing documentation from [READMEs](https://github.com/bionode/bionode-watermill/tree/master/docs) and [code comments](https://github.com/bionode/bionode-sra/blob/master/lib/bionode-sra.js#L27-L53) to website: [doc.bionode.io](http://doc.bionode.io), [index](https://github.com/bionode/doc.bionode.io/blob/master/source/index.html.md)
- [ ] Add more lessons to tutorial: [biohacker #1](https://github.com/bionode/biohacker/issues/1)
- [x] Finish the Personas and Pathways exercise: [bionode #37](https://github.com/bionode/bionode/issues/37)

### Some JavaScript knowledge required:
- [ ] Pipeline Graph (DAG) Visualization [bionode-watermill #50](https://github.com/bionode/bionode-watermill/issues/50)
- [x] Simple usage tutorial [bionode-watermill #49](https://github.com/bionode/bionode-watermill/issues/49)
- [ ] Quickly create new bionode modules from auto-generated template: [bionode #23](https://github.com/bionode/bionode/issues/23): 
- [ ] Make sure all repos use same label system and create script to generate them automatically for new repos: [bionode #39](https://github.com/bionode/bionode/issues/39)
- [x] Add insight dependency to anonymously report usage metrics: [bionode #34](https://github.com/bionode/bionode/issues/34)
- [x] Replace tests framework [mocha](https://github.com/mochajs/mocha) with [tape](https://github.com/substack/tape) to work better with [browserify](http://browserify.org): [bionode-gff #1](https://github.com/bionode/bionode-gff/issues), [bionode-fastq #5](https://github.com/bionode/bionode-fastq/issues/5)

### Challenging issues:
- [ ] Improve bionode hackathon prototype modules in [bionode-hack](http://github.com/bionode-hack) so they can be moved to [bionode](http://github.com/bionode).
- [ ] Write data analysis pipelines (e.g. [bioinformatics](https://github.com/bionode/bionode-watermill/tree/master/examples/pipelines)) using [bionode-watermill](https://github.com/bionode/bionode-watermill)
- [ ] Convert wrapper modules into Node.JS C/C++ addons: [bionode-sam #3](https://github.com/bionode/bionode-sam/issues/3)
- [ ] Prototype Common Workflow Language support: [bionode-watermill #45](https://github.com/bionode/bionode-watermill/issues/45)
- [ ] Prototype Atom.io extension: [bionode-seq #4](https://github.com/bionode/bionode-seq/issues/4)
- [ ] Explore benefits of [Nodestream](https://github.com/nodestream/nodestream) for [bionode-watermill](https://github.com/bionode/bionode-watermill): [bionode-watermill #46](https://github.com/bionode/bionode-watermill/issues/46)

**Comment by bmpvieira** [comment]
Done 😄 
https://twitter.com/bmpvieira/status/870598035964932096
